# Generated by Django 3.2.13 on 2022-06-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20220613_0411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcar',
            name='featured_car',
        ),
        migrations.AlterField(
            model_name='postcar',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
    ]
